# Every tag here = irrelevant to BIT Capital equity signals.
# If a row contains ANY of these tags it gets removed in Stage 1.

IRRELEVANT_TAGS = {

    # ── Sports ────────────────────────────────────────────────
    "Sports","NFL","NBA","MLB","NHL","MLS","WNBA","UFC",
    "Boxing","Wrestling","Golf","Tennis","Cricket","Formula 1",
    "NASCAR","Motorsports","Cycling","Skiing","Hockey",
    "Olympics","2026 Winter Games","Table Tennis","Ping Pong",
    "PGA","ATP","WTA","Combat Sports","P4P",
    "Super Bowl","NFL Playoffs","NFL Free Agency","Fantasy Football",
    "AFC","AFC East","AFC North","AFC South","AFC West",
    "NFC","NFC East","NFC North","NFC South","NFC West",
    "NBA Finals","NBA Draft","NBA Champion","2026 NBA Playoffs",
    "NCAA Basketball","NCAA CBB","CWBB","Stanley Cup",
    "World Series","MLB Playoffs","ALCS","NL Central","NL West",
    "NL east","NL MVP","AL Central","AL East","AL West","AL MVP",
    "Major League Baseball","Cy young","Platinum Glove","No-no",
    "No-hitters","Perfect game","Pitching","Batting average",
    "RBIs","Stolen bases","Home runs","Postseason","baseball",
    "Soccer","Premier League","EPL","La Liga","La Liga 2",
    "Bundesliga","bundesliga","Ligue 1","Ligue 2","Serie A",
    "Eredivisie","Champions League","UEFA Champions League",
    "UEFA Europa League","UEFA Conference League",
    "Europa Conference League","Europa League",
    "UEFA Women's Champions League","Women's Champions League",
    "Women's soccer","NWSL","Copa Libertadores","Copa Sudamericana",
    "Coppa Italia","DFB-Pokal","FA Cup","EFL Cup","EFL Championship",
    "Coupe de France","Liga MX","Primeira Liga","Liga Endesa",
    "Super Rugby Pacific","Rugby",
    "Brazil Serie A","Brazil Sèrie B","Romania SuperLiga",
    "Denmark Superliga","Norway Eliteserien","Chile Primera",
    "Saudi Professional League","Chinese Super League",
    "Australian A-League","K-league","Japan J League",
    "Japan J2 League","Morocco Botola Pro","Süper Lig",
    "TFF Super Kupa","Turkey BSL","SHL","KHL","AHL",
    "International League T20","Big Bash League","T20 Blast",
    "Bangladesh Premier League","Caribbean Premier League",
    "Legends League Cricket","Major League Cricket",
    "Rugby Top 14","United Rugby Championship",
    "Rugby Six Nations","Six Nations","International Cricket",
    "Indian Premier League","Indian Super League","IPL",
    "Volleyball","Handball","Investec Champions Cup",
    "Euroleague","Euroleague Basketball",
    "Champions League Basketball","Basketball Series A",
    "Greek Basketball League","Germany BBL","VTB United League",
    "ABA League","KBO","KBL","NBL","CBA","LNB","Pro A",
    "Roland Garros","Wimbledon","T20","Qualification","Qualifying",
    "Relegation","Colombia Primera A","Bolivia LFPB","Peru Liga 1",
    "Liga Nacional Guatemala","Liga Promerica","egypt premier league",
    "chile primera","hibachi","baseaball",
    # Sports stats
    "Goals","goals","goal","goal contributions","clean sheet",
    "clean sheets","red card","red cards","yellow card",
    "assists","assist","man of the match","motm","potm",
    "player of the match","goalkeeper","goalie","keeper",
    "golden boot","scorigami","pennant","hank aaron",
    "Comeback Player","Dexter Lawrence","George Pickens",
    "Joe Burrow","Patrick Mahomes","patrick mahomes",
    "maxx crosby","tyreek hill","travis kelce",
    # Athletes
    "Tiger Woods","Federer","Cristiano Ronaldo","Alcaraz",
    "Giannis Antetokounmpo","Milwaukee Bucks","conor mcgregor",
    "mayweather","pacquiao","floyd","Jake Paul","Joe Pyfer",
    "salah","neymar",

    # ── Esports / Gaming ─────────────────────────────────────
    "Esports","League of Legends","league of legends","Dota 2",
    "Counter-Strike","counter-strike","Call of Duty","COD",
    "Fortnite","Rocket League","Rainbow Six Siege","Overwatch",
    "Apex Legends","Mobile Legends: Bang Bang","Honor of Kings",
    "Super Smash","Starcraft","GTA VI","T1","Vitality","Mouz",
    "Team Falcons","BLAST Fort Worth","IEM Cologne","IEM Rio",
    "PGL Wallachia","PGL Bucharest","EWC 2026","lol","lol worlds",
    "Games","Game Specials","dota","counter strike 2","cs2",
    "video games","xbox",

    # ── Entertainment / Celebrity ─────────────────────────────
    "Oscars","Grammys","Emmys","BAFTA","Golden Globes",
    "Critics Choice","Music","Movies","TV","Animation",
    "Reality TV","Box Office","Culture","Celebrity","Celebrities",
    "Taylor Swift","Beyonce","Drake","Kanye","ye","Bruno Mars",
    "Charli XCX","Billie Eilish","Dua Lipa","Lana Del Rey",
    "lana del rey","SZA","Olivia Rodrigo","Sabrina Carpenter",
    "MrBeast","Logan Paul","PewDiePie","YouTube","Spotify",
    "Warner Bros","Sony","Netflix","album","song","Billboard",
    "Hot 100","hot 100","Cannes","festival","Eurovision",
    "Timothée Chalamet","Pedro Pascal","Tom Holland","anime",
    "books","art","Museum","award","Awards","Breaking News",

    # ── WWE / Pro wrestling ───────────────────────────────────
    "WWE","WrestleMania","Professional Wrestling","Cody Rhodes",
    "Roman Reigns","CM Punk","Seth Rollins","Rhea Ripley",
    "Gunther","Dominik Mysterio","Jade Cargill","Becky Lynch",
    "AJ Lee","Liv Morgan","Finn Balor","Drew McIntyre","Jacob Fatu",

    # ── Pure domestic politics (no equity angle) ─────────────
    "Alabama Midterm","Alabama Primary","Alaska Midterm","Alaska Primary",
    "Arizona Midterm","Arizona Primary","Arkansas Midterm","Arkansas Primary",
    "California Midterm","California Primary","Colorado Midterm","Colorado Primary",
    "Connecticut Midterm","Connecticut Primary","Delaware Midterm","Delaware Primary",
    "Florida Midterm","Florida Primary","Georgia Midterm","Georgia Primary",
    "Hawaii Midterm","Hawaii Primary","Idaho Midterm","Idaho Primary",
    "Illinois Midterm","Illinois Primary","Indiana Midterm","Indiana Primary",
    "Iowa Midterm","Iowa Primary","Kansas Midterm","Kansas Primary",
    "Kentucky Midterm","Kentucky Primary","Louisiana Midterm","Louisiana Primary",
    "Maine Midterm","Maine Primary","Maryland Midterm","Maryland Primary",
    "Massachusetts Midterm","Massachusetts Primary",
    "Michigan Midterm","Michigan Primary","Minnesota Midterm","Minnesota Primary",
    "Mississippi Midterm","Mississippi Primary","Missouri Midterm","Missouri Primary",
    "Montana Midterm","Montana Primary","Nebraska Midterm","Nebraska Primary",
    "Nevada Midterm","Nevada Primary","New Hampshire Midterm","New Hampshire Primary",
    "New Jersey Midterm","New Jersey Primary","New Mexico Midterm","New Mexico Primary",
    "New York Midterm","New York Primary","North Carolina Midterm","North Dakota Midterm",
    "Ohio Midterm","Ohio Primary","Oklahoma Midterm","Oklahoma Primary",
    "Oregon Midterm","Oregon Primary","Pennsylvania Midterm","Pennsylvania Primary",
    "Rhode Island Midterm","Rhode Island Primary",
    "South Carolina Midterm","South Carolina Primary",
    "South Dakota Midterm","South Dakota Primary",
    "Tennessee Midterm","Tennessee Primary","Texas Midterm","Texas Primary",
    "Texas Senate","Utah Midterm","Utah Primary","Vermont Midterm","Vermont Primary",
    "Virginia Midterm","Virginia Primary","Washington Midterm",
    "West Virginia Midterm","Wisconsin Midterm","Wisconsin Primary",
    "Wyoming Midterm","Wyoming Primary","North Carolina Primary",
    "North Dakota Primary","West Virginia Primary","Washington Primary",
    "Governor Primary","Governor midterms","Mayoral Elections","NYC Mayor",
    "Local Elections","Democratic Primary","Republican Primary",
    "House Primary","House Elections","Senate Primary","Senate midterms",
    "Primaries","Midterms","Referenda","Referendum","Vote Counting",
    "Voter ID","Voter Fraud","Voting","Ballot","ballot","votes",
    "voting","vote counting","gerrymander","redistrict","Popular Vote",
    "Elections","Nov 4 Elections","Global Elections","World Elections",
    "Macro Election 1","Macro Election 2","March 3 Primaries",
    "massachussetts primary","primary elections","primary","by election",
    "Democratic Party of Korea","People's Power Party","people power party","NATO","World",
    "Foreign Policy","Trump-Zelenskyy","Congress","us government","house","Congress","Russia Capture",
    "Ukraine Map","Trump Presidency","Trump","Military Actions","US-Iran","Middle East","putin","world affairs"
    "Israel",
    # Politicians no equity link
    "Starmer","keir","Macron","Marine Le Pen","Viktor Orban","Fidesz",
    "Tisza","Peter Magyar","Nigel Farage","Kemi Badenoch","Reform UK",
    "Labour","Liberal Democrats","Greens","Conservative",
    "Marjorie Taylor Greene","marjorie taylor greene","Tulsi Gabbard",
    "Alexandria Ocasio-Cortez","aoc","Bernie Sanders","bernie sanders",
    "Kristi Noem","kristi noem","Gavin Newsom","gavin newsom","India","Ukraine","Russia",
    "Gretchen Whitmer","Julianna Stratton","Zelenskyy","zelensky",
    "Erdogan","erdogan","Bolsonaro","Maduro","Nicolas Maduro","maduro",
    "Ramzan Kadyrov","Khanna","Cornyn","Crockett","Paxton","Noem",
    "obama","clinton","bush","fidel","Castro","castro","Talarico",
    "Hegseth","leavitt","Leavitt","rubio","Rubio","thune","Thune",
    "Mette Frederiksen","Herzog","Vance","Manu",

    # ── Religion / Culture ────────────────────────────────────
    "kippah","yamaka","Yom","Easter","Christmas","Pope","pope",
    "religion","Solstice","Prince Andrew","Royal Family",
    "King of Bahrain",

    # ── Celebrity scandal / gossip ────────────────────────────
    "pedophile","Grooming Gangs","Ghislaine Maxwell","Maxwell",
    "Epstein","Jeffrey Epstein","epstein files","andrew tate",
    "tristan tate","Tate","Luigi Mangione","mangione",
    "Sam Bankman-Fried","Carano","Rousey","Rousey vs. Carano",

    # ── Weather / Environment ─────────────────────────────────
    "Weather","Weather & Science","Earthquake","Earthquakes",
    "earthquake","Hurricane","Precipitation","Daily Temperature",
    "Climate & Science","Global Temp","Volcano","Natural Disasters",
    "Natural Disaster","hurricane","clima","climate & weather",
    "climate","Greta Thunberg",

    # ── Misc noise ────────────────────────────────────────────
    "Lottery","Powerball","Hot Dog Eating","Love Is Blind","Poker",
    "Horse Racing","Darts","Pickleball","Ballroom","Ships","ships",
    "tanker","ship","cape of good hope","Dunesday","Aliens","ufo","uap",
    "Daylight","Solstice","mcdonald's","burger","flip off",
    "middle finger","Kimi","Milady","milady",
    "Rolex index","Audemars Piguet index","Patek","Subdial","rolex","watch",
    "Mecklenburg-Vorpommern","Saxony-Anhalt","Farrer",

    # ── Junk crypto tokens ────────────────────────────────────
    "Puffpaw","MegaETH","Predict.fun","Meme Coin","Pudgy Penguins",
    "CryptoPunks","NFT","nft","Pump.Fun","GMGN","Dreamcash","Betmoar",
    "Loopscale","Kinetiq","Arcium","Ostium","Pharos","OpenGradient",
    "Gensyn","Exponent","HIP-4","HIP3","Cambria","Hurupay","Hylo",
    "QFEX","EdgeX","Decibel","Aster","Nexus","Moonshot","StandX",
    "Neutrl","Relay","Reya","Silicon Data","Ventuals","Variational",
    "Parcl","Aligned Layer","Ethereal","Airdrops","Token Sales",
    "token launch","Collectibles","Plasma","Perena","EVIV","BVIV",
    "DEHL","GRVT","SDH100RT","Abstract","MagicBlock","Nansen",

    # ── Internal Polymarket tags ──────────────────────────────
    "Depreciated3","Depreciated9","Hide From New",
    "Rewards 20","Rewards 50","Rewards 100","Rewards 200",
    "Rewards 300 4.5 50","Rewards Automation 50 4.5 50",
    "Parent For Derivative","Recurring","Daily-Close","Daily",
    "Monthly","Monthly Hit","Hit Yearly","Yearly","Extended",
    "Multi Strikes","Overnight","Up Only","Up or Down",
    "Best of 2025","Pre-Market","Featured","Other","Mentions",
    "Hit First","Hit Price","best month","Earn 4%","Huddle",
    "Polymarket","Prediction Markets","4.5","50","100","20","5M","All",
    "Macro Graph","Macro Single",

    # -- Extra Tags --
    "sports","soccer","nba","nfl","mlb","nhl","mls","uefa","match","matches","goal","goals","score","scoring","season","tournament","player","players","team","teams","esports","gaming","game","games","anime","manga","movie","movies","tv","television","show","shows","celebrity","celebrities","music","oscars","entertainment","pop culture","culture","influencer","youtube","twitch","streamer","streaming","election","elections","primary","primaries","senate","house","governor","candidate","candidates","vote","voting","poll","polls","midterm","midterms","parliament","presidency","president","campaign","debate","debates","world","global","international","diplomacy","summit","conference","meeting","speech","announcement","leadership","government","military","war","conflict","geopolitics-general","macron","trump","biden","xi","putin","zelensky","2025 predictions","2026 predictions","predictions","forecast","future","odds","betting","markets","business","economy-general","companies","industry","market sentiment","Mexico","Mexico Cartel War","mencho","California","US Election","Argentina","Zohran Mamdani","Mamdani","nyc","fraud","day care","Somali","minnesota","Minnesota Unrest","NFP","unemployement","nonfarm payroll","bls","UK","cpi","EU","Europe","Brazil","Courts","STF","tom lee","Australia","Justin Sun","South Africa","Korea","Foreign Exchange","dollar","forex","Exchange Rate","FX","Japan","Yen","pound","South Korea","GBP/USD","USD/KRW","Won","Banxico","Global Rates","Parlays","United Kingdom","Jalisco New Generation Cartel","Mexico","Mexico Cartel War","jalisco","sinaloa Cartel","El Mencho","mencho","CJNG","BOE","Interest Rate","bank rate","Global Rates","Iran", "shah","Geopolitics","Reza Pahlavi","U.S. x Iran","Iran Regime","Iran","iraq","independence","KRG","Kurds","Regional Spillover","impeach","remove","Mojtaba","ayatollah","Iran Regime","Geopolitics","Iran","Khamenei", "Mojtaba Khamenei","Khamenei out","Mojtaba out","STF","Khamenei","ayatollah","supreme leader","Khamenei","Iran Regime","Kharg Island","Mojtaba Khamenei","Iran","Israel x Iran","Regional Spillover","Israel","Hezbollah","IDF","Lebanon","Colombia","Ecuador","interest rates","European Central Bank","mbs","saudi arabia","OPEC","United Arab Emirates","UAE","budget","Banxico","Approval","BOI","Interest Rate",
}